### ISSUE TITLE
Suggestion [ Attack effect ]

### ISSUE THREAD

**Issue by Samus0754** [kindawindytoday/Minty#10]
Hi, so i have a useful hack you could add.

attack effects, that would be on the "player" category : 

- Multiple hit mode which means the user can decide how much attacks it will send (multiplier would be between 1-50)
in this category, there would some sub categories : 
- One punch mode : calculate how many hits needed to kill an enemy based on their HP, and sets the multiplier accordingly.

- Randomize multiplier : randomizes the multiplier based on the min and max multiplier (it would add 2 slides where the user would set the min and the max.

- Multi animation : This would make the character repeat the same attack animation depending on a filter which will run the animation every x seconds (max would be 3, and the user would be able to put miliseconds too ( ex : 0.5 , 0.1 etc)

- Auto weakspot : This would only work for archers, when the user fires at an enemy, it would automatically count the hit as a headshot.

- Wall hack (only archers) : With ESP, when you shoot trough a wall, it would ignore it and touch them.

- Aimbot (only archers) : When the users aim, it would automatically aim at the Lowest distance / Lowest health / highest distance / highest health to an enemy. Would work good with auto weakspot.

Hope this will help improve your project ! I have a lot of suggestions in mind, but i'll let you add theses for the moment :)

**Comment by Moistcrafter** [comment]
Our project’s goal is not for such hacks like those that exist in Akebi.

**Comment by Moistcrafter** [comment]
because our project is not a cheat.
